#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication foamCleanCase
runApplication blockMesh
#runApplication refineMesh
runApplication foamRun &
#while [ ! -f postProcessing/residuals/0/residuals.dat ]; do
#  sleep 1
#done
#foamMonitor -t $xNet2 -l postProcessing/residuals/0/residuals.dat
#------------------------------------------------------------------------------
